# Generated by Django 3.2.3 on 2021-06-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWBO_Projekt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(),
        ),
    ]
