# Generated by Django 3.2.3 on 2021-06-24 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SWBO_Projekt', '0004_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mother_post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='SWBO_Projekt.post'),
        ),
    ]
