# Generated by Django 3.2.3 on 2021-06-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWBO_Projekt', '0005_alter_comment_mother_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('book_1', models.IntegerField(default=0)),
                ('book_2', models.IntegerField(default=0)),
                ('book_3', models.IntegerField(default=0)),
                ('book_hobbit', models.IntegerField(default=0)),
            ],
        ),
    ]
