# Generated by Django 3.2.3 on 2021-06-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWBO_Projekt', '0006_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordbyCharcter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=50)),
                ('chapter', models.IntegerField(default=0)),
                ('character', models.CharField(max_length=50)),
                ('race', models.CharField(max_length=50)),
                ('words', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='book_1',
        ),
        migrations.RemoveField(
            model_name='character',
            name='book_2',
        ),
        migrations.RemoveField(
            model_name='character',
            name='book_3',
        ),
        migrations.RemoveField(
            model_name='character',
            name='book_hobbit',
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='url',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
