# Generated by Django 3.2.3 on 2021-06-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWBO_Projekt', '0008_auto_20210625_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='url',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='wordbycharcter',
            name='chapter',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
